project:
  type: website
  output-dir: public

title-block-style: default
title-block-banner: true

website:
  title: "MA{VR}X Lab"
  reader-mode: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/
        text: About
      - href: posts.qmd
        text: Posts
      - href: events.qmd
        text: Events
      - href: resources/
        text: Resources
  page-footer: 
    left: "Copyright 2022, Ryan Straight" 
    right: 
      - icon: github
        href: https://github.com/mavrxlab/
      - icon: mastodon 
        href: https://hci.social/@mavrxlab/
format:
  html:
#    theme: materia
    css: styles.css
    toc: true
    include-in-header:
      - fonts.html
    citations-hover: true
    footnotes-hover: true




